version: '3.8'

services:
  naukri-bot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NAUKRI_EMAILID=${NAUKRI_EMAILID}
      - NAUKRI_PASSWORD=${NAUKRI_PASSWORD}
      - BOT_EMAILID=${BOT_EMAILID}
      - BOT_MAIL_PASSWORD=${BOT_MAIL_PASSWORD}
      - RECEIVEING_EMAILID=${RECEIVEING_EMAILID}
    volumes:
      - .:/usr/src/app
