# Use an official Node.js runtime as a parent image
FROM node:16-slim

# Install necessary dependencies for Puppeteer
RUN apt-get update && \
    apt-get install -y \
    wget \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libgdk-pixbuf2.0-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libxss1 \
    libxtst6 \
    libxshm0 \
    xdg-utils \
    --no-install-recommends

# Install Puppeteer dependencies
RUN apt-get install -y \
    gconf-service \
    libgconf-2-4 \
    libnss3 \
    libxkbcommon0 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libxss1 \
    libxtst6 \
    libnss3 \
    libgdk-pixbuf2.0-0 \
    libasound2 \
    libx11-xcb1 \
    libgbm1 \
    libdrm2 \
    libwayland-client0 \
    libwayland-server0 \
    libxshmfence1 \
    --no-install-recommends

# Install Puppeteer
RUN npm install -g puppeteer

# Create and set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port
EXPOSE 5000

# Command to run the application
CMD [ "node", "index.js" ]
